### ISSUE TITLE
cannot get back current location after previewing a url

### ISSUE THREAD

**Issue by Johann150** [jansc/ncgopher#15]
**Is your feature request related to a problem? Please describe.**
When previewing a URL using <kbd>i</kbd> this overwrites the status line. Since the status line often holds the URL the client is currently at, there is now no easy way of telling at which URL the client is.

**Describe the solution you'd like**
Preferably by pressing <kbd>i</kbd> again or by using another key binding the current URL should again be displayed in the status bar.

**Describe alternatives you've considered**
The history should usually contain the last visited URL, but opening up the history for such a small thing seems a bit overkill, and it also requires at least two key strokes (if the right menu entry was selected previously): <kbd>Esc</kbd> <kbd>↵</kbd>.

As a first idea I thought the last url could just be loaded from the history and then displayed in the status line. But if the user has just cleared the history, that url will not be available.

Something completely different that would also solve the problem would be to display the actual url instead of just "Gophermap" or "Gemini" at the top of the view.

**Comment by jansc** [comment]
I agree that the current behavior is a bit odd. Pressing `i` once more is probably the most simple way to improve this.

**Comment by Johann150** [comment]
Seeing that things like timeouts do also overwrite the status line, I think the solution of displaying the URL at the top would be the better solution.

**Comment by jansc** [comment]
I've added the current URL to the title at the top.

**Comment by Johann150** [comment]
I also tried to implement it but got caught up in some more refactoring. And I think my solution is simpler. Should I still make a PR for it?
