### ISSUE TITLE
Segfault on cargo build on openbsd

### ISSUE THREAD

**Issue by jamestomasino** [jansc/ncgopher#2]
```bash
...
Downloaded arc-swap v0.4.6            
Segmentation fault (core dumped)
```
I'm trying to install this on tilde.black. I have no experience working in or compiling rust things outside of README files.

**Comment by jansc** [comment]
That could be pretty much anything. I will try to create an account on tilde.black and see what I can find out!

**Comment by jansc** [comment]
Not sure what the problem here was, but OpenBSD 6.6 comes with Rust 1.38.0, so I had to downgrade rusqlite to make it compile:
```
index 0b35418..fab3bf9 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -32,7 +32,7 @@ config = "0.10.1"
 serde_derive = "1.0.106"
 serde = { version = "1.0.106", features = ["derive"] }
 toml = "0.5.6"
-rusqlite = { version = "0.23.1", features = ["url", "chrono"] }
+rusqlite = { version = "0.20.0", features = ["url", "chrono"] }
 regex = "1.3.7"
 textwrap = "0.11.0"
 ```
