### ISSUE TITLE
Periods at the beginning of a line are not handled according to Gopher RFC

### ISSUE THREAD

**Issue by nortti0** [jansc/ncgopher#210]
**Describe the bug**
When ncgopher displays a text file (itemtype 0, though the same bug probably also exists for other itemtypes using the default transfer mode like 1, 6, and 7), it seemingly does not do anything about periods at the beginning of the line.

**To Reproduce**
1. Go to 'gopher://yurie.smar.fi:7070/0/dots.txt'
2. The text file is displayed as:

>foo
>..
>...
>..bar
>...baz
>.

**Expected behavior**
The text file should be displayed as:

>foo
>.
>..
>.bar
>..baz

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 12

**Additional context**
[RFC1436 The Internet Gopher Protocol (a distributed document search and retrieval protocol)](https://www.rfc-editor.org/rfc/rfc1436.html) states (in section 2, The internet Gopher Model):

>The server responds with a block of text terminated with a period on a line by itself, and closes the connection.

The final ".\r\n" is therefore part of the protocol, not contents of the text file.

It further states (in Appendix, under "Textfile Entity"):

>Note:  Lines beginning with periods must be prepended with an extra period to ensure that the transmission is not terminated early. The client should strip extra periods at the beginning of the line.

Therefore the extra periods at the beginning of lines should be stripped, as they are again part of the protocol, not file contents.

**Comment by jansc** [comment]
Thanks for the report! I've committed a fix in the master branch.
Btw, both lynx, curl and gopher on Debian seem to handle double dots the same way ncgopher did.

Thanks a lot for using ncgopher :)

**Comment by nortti0** [comment]
Tried with the newest master, and it appears to now be removing periods from start of gophermap entries, e.g.

`i.start with a period			`

will display as just

>starts with a period

**Comment by nortti0** [comment]
Both gophermaps and plain text files seem to be working as expected now.

**Comment by jansc** [comment]
That's good news. Thanks :)
