### ISSUE TITLE
Attempting to browse gopherpedia gives an error message

### ISSUE THREAD

**Issue by OmnipotentEntity** [jansc/ncgopher#3]
**Description of the problem:**

When attempting to browse gopherpedia using the provided links to articles, an error message is displayed:

```
i   ____                        _	null	(FALSE)	0
i  / __ \                      | |	null	(FALSE)	0
i | |  | | ___   ___  _ __  ___| |	null	(FALSE)	0
i | |  | |/ _ \ / _ \| '_ \/ __| |	null	(FALSE)	0
i | |__| | (_) | (_) | |_) \__ \_|	null	(FALSE)	0
i  \____/ \___/ \___/| .__/|___(_)	null	(FALSE)	0
i                    | |	null	(FALSE)	0
i                    |_|	null	(FALSE)	0
i	null	(FALSE)	0
iLooks like something went wrong with that request	null	(FALSE)	0
i	null	(FALSE)	0
i	null	(FALSE)	0
3Error 400	null	(FALSE)	0
i	null	(FALSE)	0
i	null	(FALSE)	0
1back to gopherpedia	/	gopherpedia.com	70

.
```

However, manually entering the URL directly resolves the page without issue.  This issue is not observed when using the [floodgap gopher proxy](https://gopher.floodgap.com/gopher/gw?gopher%3A%2F%2Fgopherpedia.com%2F1)

Built from source using git tag v0.1.5

**Steps to reproduce:**

1. Whack g and type in: `gopherpedia.com/1`
2. Arrow down to an article link (such as [Superbook](https://gopher.floodgap.com/gopher/gw?=gopherpedia.com+70+302f5375706572626f6f6b))
3. Press Enter to follow the link

**Expected results:**

The page content of the article.

**Actual results:**

The previously quoted error message.

**Comment by OmnipotentEntity** [comment]
After relaunching the executable, I can no longer reproduce this error.

**Comment by jansc** [comment]
Glad you found a solution!
