### ISSUE TITLE
ncgopher fails to build after update to rust-1.54

### ISSUE THREAD

**Issue by 0323pin** [jansc/ncgopher#35]
Hi,

I'm the NetBSD package maintainer for `ncgopher`,  it no longer builds on NetBSD after updating to rust-1.54.0

 - OS: NetBSD
 - Version: current, rolling
 - Rust: 1.54.0

This week Rust was updated from 1.52.1 to 1.54.0
After this update, two independent builds have reported that `ncgopher` fails to build.
While we were using 1.52.1, the package always built fine and no changes to the package were done during this time.

Please find a build reports here, https://us-east.manta.joyent.com/pkgsrc/public/reports/NetBSD/trunk/x86_64/20210911.1245/ncgopher-0.2.0nb1/build.log and here, http://www.ki.nu/pkgsrc/reports/current/NetBSD-9.0/20210911.0116/ncgopher-0.2.0nb1/build.log

Don't know if you can do much about it as the error seams to be on `lexical-core` but, thought I'd let you know.

Regards

EDIT: see, https://github.com/Alexhuszagh/rust-lexical/issues/55
It might be enough to update `lexical-core`.

EDIT2: cargo tree outputs the following, https://pastebin.com/QE5qyy3p
More than one entry for `lexical-core`, maybe better to bump all dependencies and get things up-to-speed.

**Comment by Johann150** [comment]
I could not reproduce this issue with neither Rust 1.54.0 nor the latest stable on Linux (i.e. rustup toolchain `stable-x86_64-unknown-linux-gnu`).

I updated the dependencies in 2b4f666882a397b6e859d655ff88dfdf268cee4e (it's just running `cargo update`).

**Comment by 0323pin** [comment]
>I updated the dependencies in 2b4f666
Thanks

>it's just running cargo update
No, not for packaging it. We need a release tag.

**Comment by 0323pin** [comment]
@Johann150 I've just built `ncgopher` from 2b4f666 and it compleated successfully.
I'll bump the package revison and merge the build from this single commit, better to do this over providing a broken package with the stable release. Thanks!
