### ISSUE TITLE
Tag 0.3.0 on Github

### ISSUE THREAD

**Issue by 0323pin** [jansc/ncgopher#37]
Hi,
NetBSD package maintainer here.
Just saw that 0.3.0 has been released on crates.io

Could you please provide a release tag here on Github as well so I can update the NetBSD package?

Thank you.

**Comment by 0323pin** [comment]
Sorry for the noise, I see the tag now but, not as a release, simply a tag. Should be enough to get the update done, though.

Giving it a shot when time is available :)

**Comment by 0323pin** [comment]
All good, merging the update in a few minutes.

**Comment by jansc** [comment]
Sorry for the late answer. I'm not sure why no release was generated. Still investigating...

**Comment by 0323pin** [comment]
@jansc inga problem, https://mail-index.netbsd.org/pkgsrc-changes/2021/11/23/msg243830.html
