### ISSUE TITLE
Can't open gopher page with space in URL

### ISSUE THREAD

**Issue by austinsheep** [jansc/ncgopher#78]
**Description**
Receive an error when navigating to `gopher://gopherpedia.com/0/Tor%20(network)`

I'm assuming this is due to the URL percent encoding/decoding as Gopherpedia pages without a space in the URL appear to have no issue.

**To Reproduce:**
1. Go to gopher://gopherpedia.com
2. Search for 'Tor'
3. Click on 'Tor (network)'
5. See error

**Comment by jansc** [comment]
Thanks for the report! For some reason the notification from your issue never appeared in my inbox, so sorry for the late answer. I'll look into it asap.
