### ISSUE TITLE
missing installation instructions (Linux)

### ISSUE THREAD

**Issue by Johann150** [jansc/ncgopher#8]
**Describe the bug**
The crate depends on the external ncurses, openssl and sqlite3 libraries. These dependencies have to be installed manually because they are C libraries and are thus not installed by cargo.

**To Reproduce**
1. run `cargo install ncgopher` as per the current installation instructions
2. see build error about ncurses
3. install ncurses
4. rerun `cargo install ncgopher`
5. see build error about openssl
6. install openssl
7. rerun `cargo install ncgopher`
8. see linker error "cannot find -lsqlite3"
9. install sqlite3
10. rerun `cargo install ncgopher`
11. finally installed

**Expected behavior:**
Install in one go without tracking down which dependencies to install.

**Desktop:**
 - OS: Linux Debian
 - Version 4.19146-1

**Additional context**
When using apt, the libraries can be installed with `sudo apt install pkg-config libncurses-dev libssl-dev libsqlite3-dev`.

**Comment by Johann150** [comment]
I can create a PR to put this in the readme, but I don't know if there should also be instructions for other operating systems.

**Comment by jansc** [comment]
I know there is a NixOS package available somewhere. A pull request for debian/ubuntu linux installation instructions would be perfect!

**Comment by jansc** [comment]
And thanks reporting this issue :)
