### ISSUE TITLE
ncgopher is missing from Arch?

### ISSUE THREAD

**Issue by SeriousBug** [jansc/ncgopher#80]
**Describe the bug**
The readme describes that you can use `sudo pacman -S ncgopher` on Arch to install ncgopher, but it's not available on Arch repos. Did it get removed for some reason? Or did you mean to refer to the `ncgopher-git` package on AUR?

**To Reproduce**
1. Run 'sudo pacman -S ncgopher`
2. It will fail because it's not in the repos

**Expected behavior**
Arch instructions should be updated if ncgopher is not available

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ArchLinux

**Additional context**

**Comment by jansc** [comment]
Thanks for your report! You are of course right, the correct package name for AUR is `ncgopher-git`. I've corrected the README-file.

**Comment by 6R1MR34P3R** [comment]
The package on the AUR has been broken (and now marked as orphaned) for more than a year now. Is this project still active?
